<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CountrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        //
        DB::table('countries')->delete();
        $countries = array(
            array('id' => 1, 'country_code' => 'AF', 'country_name' => "Afghanistan", 'country_phone_code' => '+93', 'country_status' => '1'),
            array('id' => 2, 'country_code' => 'AL', 'country_name' => "Albania", 'country_phone_code' => '+355', 'country_status' => '1'),
            array('id' => 3, 'country_code' => 'DZ', 'country_name' => "Algeria", 'country_phone_code' => '+213', 'country_status' => '1'),
            array('id' => 4, 'country_code' => 'AD', 'country_name' => "Andorra", 'country_phone_code' => '+376', 'country_status' => '1'),
            array('id' => 5, 'country_code' => 'AO', 'country_name' => "Angola", 'country_phone_code' => '+244', 'country_status' => '1'),
            array('id' => 6, 'country_code' => 'AI', 'country_name' => "Anguilla", 'country_phone_code' => '+1264', 'country_status' => '1'),
            array('id' => 7, 'country_code' => 'AQ', 'country_name' => "Antarctica", 'country_phone_code' => '+672', 'country_status' => '1'),
            array('id' => 8, 'country_code' => 'AG', 'country_name' => "Antigua and Barbuda", 'country_phone_code' => '+1268', 'country_status' => '1'),
            array('id' => 9, 'country_code' => 'AR', 'country_name' => "Argentina", 'country_phone_code' => '+54', 'country_status' => '1'),
            array('id' => 10, 'country_code' => 'AM', 'country_name' => "Armenia", 'country_phone_code' => '+374', 'country_status' => '1'),
            array('id' => 11, 'country_code' => 'AW', 'country_name' => "Aruba", 'country_phone_code' => '+297', 'country_status' => '1'),
            array('id' => 12, 'country_code' => 'AU', 'country_name' => "Australia", 'country_phone_code' => '+61', 'country_status' => '1'),
            array('id' => 13, 'country_code' => 'AT', 'country_name' => "Austria", 'country_phone_code' => '+43', 'country_status' => '1'),
            array('id' => 14, 'country_code' => 'AZ', 'country_name' => "Azerbaijan", 'country_phone_code' => '+994', 'country_status' => '1'),
            array('id' => 15, 'country_code' => 'BS', 'country_name' => "Bahamas", 'country_phone_code' => '+1242', 'country_status' => '1'),
            array('id' => 16, 'country_code' => 'BH', 'country_name' => "Bahrain", 'country_phone_code' => '+973', 'country_status' => '1'),
            array('id' => 17, 'country_code' => 'BD', 'country_name' => "Bangladesh", 'country_phone_code' => '+880', 'country_status' => '1'),
            array('id' => 18, 'country_code' => 'BB', 'country_name' => "Barbados", 'country_phone_code' => '+1246', 'country_status' => '1'),
            array('id' => 19, 'country_code' => 'BY', 'country_name' => "Belarus", 'country_phone_code' => '+375', 'country_status' => '1'),
            array('id' => 20, 'country_code' => 'BE', 'country_name' => "Belgium", 'country_phone_code' => '+32', 'country_status' => '1'),
            array('id' => 21, 'country_code' => 'BZ', 'country_name' => "Belize", 'country_phone_code' => '+501', 'country_status' => '1'),
            array('id' => 22, 'country_code' => 'BJ', 'country_name' => "Benin", 'country_phone_code' => '+229', 'country_status' => '1'),
            array('id' => 23, 'country_code' => 'BM', 'country_name' => "Bermuda", 'country_phone_code' => '+1441', 'country_status' => '1'),
            array('id' => 24, 'country_code' => 'BT', 'country_name' => "Bhutan", 'country_phone_code' => '+975', 'country_status' => '1'),
            array('id' => 25, 'country_code' => 'BO', 'country_name' => "Bolivia", 'country_phone_code' => '+591', 'country_status' => '1'),
            array('id' => 26, 'country_code' => 'BA', 'country_name' => "Bosnia and Herzegovina", 'country_phone_code' => '+387', 'country_status' => '1'),
            array('id' => 27, 'country_code' => 'BW', 'country_name' => "Botswana", 'country_phone_code' => '+267', 'country_status' => '1'),
            array('id' => 28, 'country_code' => 'BV', 'country_name' => "Bouvet Island", 'country_phone_code' => '+0', 'country_status' => '1'),
            array('id' => 29, 'country_code' => 'BR', 'country_name' => "Brazil", 'country_phone_code' => '+55', 'country_status' => '1'),
            array('id' => 30, 'country_code' => 'IO', 'country_name' => "British Indian Ocean Territory", 'country_phone_code' => '+246', 'country_status' => '1'),
            array('id' => 31, 'country_code' => 'VG', 'country_name' => "British Virgin Islands", 'country_phone_code' => '+1284', 'country_status' => '1'),
            array('id' => 32, 'country_code' => 'BN', 'country_name' => "Brunei", 'country_phone_code' => '+673', 'country_status' => '1'),
            array('id' => 33, 'country_code' => 'BG', 'country_name' => "Bulgaria", 'country_phone_code' => '+359', 'country_status' => '1'),
            array('id' => 34, 'country_code' => 'BF', 'country_name' => "Burkina Faso", 'country_phone_code' => '+226', 'country_status' => '1'),
            array('id' => 35, 'country_code' => 'BI', 'country_name' => "Burundi", 'country_phone_code' => '+257', 'country_status' => '1'),
            array('id' => 36, 'country_code' => 'KH', 'country_name' => "Cambodia", 'country_phone_code' => '+855', 'country_status' => '1'),
            array('id' => 37, 'country_code' => 'CM', 'country_name' => "Cameroon", 'country_phone_code' => '+237', 'country_status' => '1'),
            array('id' => 38, 'country_code' => 'CA', 'country_name' => "Canada", 'country_phone_code' => '+1', 'country_status' => '1'),
            array('id' => 39, 'country_code' => 'CV', 'country_name' => "Cape Verde", 'country_phone_code' => '+238', 'country_status' => '1'),
            array('id' => 40, 'country_code' => 'KY', 'country_name' => "Cayman Islands", 'country_phone_code' => '+1345', 'country_status' => '1'),
            array('id' => 41, 'country_code' => 'CF', 'country_name' => "Central African Republic", 'country_phone_code' => '+236', 'country_status' => '1'),
            array('id' => 42, 'country_code' => 'TD', 'country_name' => "Chad", 'country_phone_code' => '+235', 'country_status' => '1'),
            array('id' => 43, 'country_code' => 'CL', 'country_name' => "Chile", 'country_phone_code' => '+56', 'country_status' => '1'),
            array('id' => 44, 'country_code' => 'CN', 'country_name' => "China", 'country_phone_code' => '+86', 'country_status' => '1'),
            array('id' => 45, 'country_code' => 'CX', 'country_name' => "Christmas Island", 'country_phone_code' => '+61', 'country_status' => '1'),
            array('id' => 46, 'country_code' => 'CC', 'country_name' => "Cocos Islands", 'country_phone_code' => '+61', 'country_status' => '1'),
            array('id' => 47, 'country_code' => 'CO', 'country_name' => "Colombia", 'country_phone_code' => '+57', 'country_status' => '1'),
            array('id' => 48, 'country_code' => 'KM', 'country_name' => "Comoros", 'country_phone_code' => '+269', 'country_status' => '1'),
            array('id' => 49, 'country_code' => 'CG', 'country_name' => "Congo", 'country_phone_code' => '+242', 'country_status' => '1'),
            array('id' => 50, 'country_code' => 'CK', 'country_name' => "Cook Islands", 'country_phone_code' => '+682', 'country_status' => '1'),
            array('id' => 51, 'country_code' => 'CR', 'country_name' => "Costa Rica", 'country_phone_code' => '+506', 'country_status' => '1'),
            array('id' => 52, 'country_code' => 'HR', 'country_name' => "Croatia", 'country_phone_code' => '+385', 'country_status' => '1'),
            array('id' => 53, 'country_code' => 'CU', 'country_name' => "Cuba", 'country_phone_code' => '+53', 'country_status' => '1'),
            array('id' => 54, 'country_code' => 'CY', 'country_name' => "Cyprus", 'country_phone_code' => '+357', 'country_status' => '1'),
            array('id' => 55, 'country_code' => 'CZ', 'country_name' => "Czech Republic", 'country_phone_code' => '+420', 'country_status' => '1'),
            array('id' => 56, 'country_code' => 'CD', 'country_name' => "Democratic Republic of the Congo", 'country_phone_code' => '+243', 'country_status' => '1'),
            array('id' => 57, 'country_code' => 'DK', 'country_name' => "Denmark", 'country_phone_code' => '+45', 'country_status' => '1'),
            array('id' => 58, 'country_code' => 'DJ', 'country_name' => "Djibouti", 'country_phone_code' => '+253', 'country_status' => '1'),
            array('id' => 59, 'country_code' => 'DM', 'country_name' => "Dominica", 'country_phone_code' => '+1767', 'country_status' => '1'),
            array('id' => 60, 'country_code' => 'DO', 'country_name' => "Dominican Republic", 'country_phone_code' => '+1809', 'country_status' => '1'),
            array('id' => 61, 'country_code' => 'TL', 'country_name' => "East Timor", 'country_phone_code' => '+670', 'country_status' => '1'),
            array('id' => 62, 'country_code' => 'EC', 'country_name' => "Ecuador", 'country_phone_code' => '+593', 'country_status' => '1'),
            array('id' => 63, 'country_code' => 'EG', 'country_name' => "Egypt", 'country_phone_code' => '+20', 'country_status' => '1'),
            array('id' => 64, 'country_code' => 'SV', 'country_name' => "El Salvador", 'country_phone_code' => '+503', 'country_status' => '1'),
            array('id' => 65, 'country_code' => 'GQ', 'country_name' => "Equatorial Guinea", 'country_phone_code' => '+240', 'country_status' => '1'),
            array('id' => 66, 'country_code' => 'ER', 'country_name' => "Eritrea", 'country_phone_code' => '+291', 'country_status' => '1'),
            array('id' => 67, 'country_code' => 'EE', 'country_name' => "Estonia", 'country_phone_code' => '+372', 'country_status' => '1'),
            array('id' => 68, 'country_code' => 'ET', 'country_name' => "Ethiopia", 'country_phone_code' => '+251', 'country_status' => '1'),
            array('id' => 69, 'country_code' => 'FK', 'country_name' => "Falkland Islands", 'country_phone_code' => '+500', 'country_status' => '1'),
            array('id' => 70, 'country_code' => 'FO', 'country_name' => "Faroe Islands", 'country_phone_code' => '+298', 'country_status' => '1'),
            array('id' => 71, 'country_code' => 'FJ', 'country_name' => "Fiji", 'country_phone_code' => '+679', 'country_status' => '1'),
            array('id' => 72, 'country_code' => 'FI', 'country_name' => "Finland", 'country_phone_code' => '+358', 'country_status' => '1'),
            array('id' => 73, 'country_code' => 'FR', 'country_name' => "France", 'country_phone_code' => '+33', 'country_status' => '1'),
            array('id' => 74, 'country_code' => 'GF', 'country_name' => "French Guiana", 'country_phone_code' => '+594', 'country_status' => '1'),
            array('id' => 75, 'country_code' => 'PF', 'country_name' => "French Polynesia", 'country_phone_code' => '+689', 'country_status' => '1'),
            array('id' => 76, 'country_code' => 'TF', 'country_name' => "French Southern Territories", 'country_phone_code' => '+0', 'country_status' => '1'),
            array('id' => 77, 'country_code' => 'GA', 'country_name' => "Gabon", 'country_phone_code' => '+241', 'country_status' => '1'),
            array('id' => 78, 'country_code' => 'GM', 'country_name' => "Gambia", 'country_phone_code' => '+220', 'country_status' => '1'),
            array('id' => 79, 'country_code' => 'GE', 'country_name' => "Georgia", 'country_phone_code' => '+995', 'country_status' => '1'),
            array('id' => 80, 'country_code' => 'DE', 'country_name' => "Germany", 'country_phone_code' => '+49', 'country_status' => '1'),
            array('id' => 81, 'country_code' => 'GH', 'country_name' => "Ghana", 'country_phone_code' => '+233', 'country_status' => '1'),
            array('id' => 82, 'country_code' => 'GI', 'country_name' => "Gibraltar", 'country_phone_code' => '+350', 'country_status' => '1'),
            array('id' => 83, 'country_code' => 'GR', 'country_name' => "Greece", 'country_phone_code' => '+30', 'country_status' => '1'),
            array('id' => 84, 'country_code' => 'GL', 'country_name' => "Greenland", 'country_phone_code' => '+299', 'country_status' => '1'),
            array('id' => 85, 'country_code' => 'GD', 'country_name' => "Grenada", 'country_phone_code' => '+1473', 'country_status' => '1'),
            array('id' => 86, 'country_code' => 'GP', 'country_name' => "Guadeloupe", 'country_phone_code' => '+590', 'country_status' => '1'),
            array('id' => 87, 'country_code' => 'GU', 'country_name' => "Guam", 'country_phone_code' => '+1671', 'country_status' => '1'),
            array('id' => 88, 'country_code' => 'GT', 'country_name' => "Guatemala", 'country_phone_code' => '+502', 'country_status' => '1'),
            array('id' => 89, 'country_code' => 'GN', 'country_name' => "Guinea", 'country_phone_code' => '+224', 'country_status' => '1'),
            array('id' => 90, 'country_code' => 'GW', 'country_name' => "Guinea-Bissau", 'country_phone_code' => '+245', 'country_status' => '1'),
            array('id' => 91, 'country_code' => 'GY', 'country_name' => "Guyana", 'country_phone_code' => '+592', 'country_status' => '1'),
            array('id' => 92, 'country_code' => 'HT', 'country_name' => "Haiti", 'country_phone_code' => '+509', 'country_status' => '1'),
            array('id' => 93, 'country_code' => 'HM', 'country_name' => "Heard Island and McDonald Islands", 'country_phone_code' => '+0', 'country_status' => '1'),
            array('id' => 94, 'country_code' => 'HN', 'country_name' => "Honduras", 'country_phone_code' => '+504', 'country_status' => '1'),
            array('id' => 95, 'country_code' => 'HK', 'country_name' => "Hong Kong", 'country_phone_code' => '+852', 'country_status' => '1'),
            array('id' => 96, 'country_code' => 'HU', 'country_name' => "Hungary", 'country_phone_code' => '+36', 'country_status' => '1'),
            array('id' => 97, 'country_code' => 'IS', 'country_name' => "Iceland", 'country_phone_code' => '+354', 'country_status' => '1'),
            array('id' => 98, 'country_code' => 'IN', 'country_name' => "India", 'country_phone_code' => '+91', 'country_status' => '1'),
            array('id' => 99, 'country_code' => 'ID', 'country_name' => "Indonesia", 'country_phone_code' => '+62', 'country_status' => '1'),
            array('id' => 100, 'country_code' => 'IR', 'country_name' => "Iran", 'country_phone_code' => '+98', 'country_status' => '1'),
            array('id' => 101, 'country_code' => 'IQ', 'country_name' => "Iraq", 'country_phone_code' => '+964', 'country_status' => '1'),
            array('id' => 102, 'country_code' => 'IE', 'country_name' => "Ireland", 'country_phone_code' => '+353', 'country_status' => '1'),
            array('id' => 103, 'country_code' => 'IL', 'country_name' => "Israel", 'country_phone_code' => '+972', 'country_status' => '1'),
            array('id' => 104, 'country_code' => 'IT', 'country_name' => "Italy", 'country_phone_code' => '+39', 'country_status' => '1'),
            array('id' => 105, 'country_code' => 'CI', 'country_name' => "Ivory Coast", 'country_phone_code' => '+225', 'country_status' => '1'),
            array('id' => 106, 'country_code' => 'JM', 'country_name' => "Jamaica", 'country_phone_code' => '+1876', 'country_status' => '1'),
            array('id' => 107, 'country_code' => 'JP', 'country_name' => "Japan", 'country_phone_code' => '+81', 'country_status' => '1'),
            array('id' => 108, 'country_code' => 'JO', 'country_name' => "Jordan", 'country_phone_code' => '+962', 'country_status' => '1'),
            array('id' => 109, 'country_code' => 'KZ', 'country_name' => "Kazakhstan", 'country_phone_code' => '+7', 'country_status' => '1'),
            array('id' => 110, 'country_code' => 'KE', 'country_name' => "Kenya", 'country_phone_code' => '+254', 'country_status' => '1'),
            array('id' => 111, 'country_code' => 'KI', 'country_name' => "Kiribati", 'country_phone_code' => '+686', 'country_status' => '1'),
            array('id' => 112, 'country_code' => 'KW', 'country_name' => "Kuwait", 'country_phone_code' => '+965', 'country_status' => '1'),
            array('id' => 113, 'country_code' => 'KG', 'country_name' => "Kyrgyzstan", 'country_phone_code' => '+996', 'country_status' => '1'),
            array('id' => 114, 'country_code' => 'LA', 'country_name' => "Laos", 'country_phone_code' => '+856', 'country_status' => '1'),
            array('id' => 115, 'country_code' => 'LV', 'country_name' => "Latvia", 'country_phone_code' => '+371', 'country_status' => '1'),
            array('id' => 116, 'country_code' => 'LB', 'country_name' => "Lebanon", 'country_phone_code' => '+961', 'country_status' => '1'),
            array('id' => 117, 'country_code' => 'LS', 'country_name' => "Lesotho", 'country_phone_code' => '+266', 'country_status' => '1'),
            array('id' => 118, 'country_code' => 'LR', 'country_name' => "Liberia", 'country_phone_code' => '+231', 'country_status' => '1'),
            array('id' => 119, 'country_code' => 'LY', 'country_name' => "Libya", 'country_phone_code' => '+218', 'country_status' => '1'),
            array('id' => 120, 'country_code' => 'LI', 'country_name' => "Liechtenstein", 'country_phone_code' => '+423', 'country_status' => '1'),
            array('id' => 121, 'country_code' => 'LT', 'country_name' => "Lithuania", 'country_phone_code' => '+370', 'country_status' => '1'),
            array('id' => 122, 'country_code' => 'LU', 'country_name' => "Luxembourg", 'country_phone_code' => '+352', 'country_status' => '1'),
            array('id' => 123, 'country_code' => 'MO', 'country_name' => "Macao", 'country_phone_code' => '+853', 'country_status' => '1'),
            array('id' => 124, 'country_code' => 'MK', 'country_name' => "Macedonia", 'country_phone_code' => '+389', 'country_status' => '1'),
            array('id' => 125, 'country_code' => 'MG', 'country_name' => "Madagascar", 'country_phone_code' => '+261', 'country_status' => '1'),
            array('id' => 126, 'country_code' => 'MW', 'country_name' => "Malawi", 'country_phone_code' => '+265', 'country_status' => '1'),
            array('id' => 127, 'country_code' => 'MY', 'country_name' => "Malaysia", 'country_phone_code' => '+60', 'country_status' => '1'),
            array('id' => 128, 'country_code' => 'MV', 'country_name' => "Maldives", 'country_phone_code' => '+960', 'country_status' => '1'),
            array('id' => 129, 'country_code' => 'ML', 'country_name' => "Mali", 'country_phone_code' => '+223', 'country_status' => '1'),
            array('id' => 130, 'country_code' => 'MT', 'country_name' => "Malta", 'country_phone_code' => '+356', 'country_status' => '1'),
            array('id' => 131, 'country_code' => 'MH', 'country_name' => "Marshall Islands", 'country_phone_code' => '+692', 'country_status' => '1'),
            array('id' => 132, 'country_code' => 'MQ', 'country_name' => "Martinique", 'country_phone_code' => '+596', 'country_status' => '1'),
            array('id' => 133, 'country_code' => 'MR', 'country_name' => "Mauritania", 'country_phone_code' => '+222', 'country_status' => '1'),
            array('id' => 134, 'country_code' => 'MU', 'country_name' => "Mauritius", 'country_phone_code' => '+230', 'country_status' => '1'),
            array('id' => 135, 'country_code' => 'YT', 'country_name' => "Mayotte", 'country_phone_code' => '+262', 'country_status' => '1'),
            array('id' => 136, 'country_code' => 'MX', 'country_name' => "Mexico", 'country_phone_code' => '+52', 'country_status' => '1'),
            array('id' => 137, 'country_code' => 'FM', 'country_name' => "Micronesia", 'country_phone_code' => '+691', 'country_status' => '1'),
            array('id' => 138, 'country_code' => 'MD', 'country_name' => "Moldova", 'country_phone_code' => '+373', 'country_status' => '1'),
            array('id' => 139, 'country_code' => 'MC', 'country_name' => "Monaco", 'country_phone_code' => '+377', 'country_status' => '1'),
            array('id' => 140, 'country_code' => 'MN', 'country_name' => "Mongolia", 'country_phone_code' => '+976', 'country_status' => '1'),
            array('id' => 141, 'country_code' => 'ME', 'country_name' => "Montenegro", 'country_phone_code' => '+382', 'country_status' => '1'),
            array('id' => 142, 'country_code' => 'MS', 'country_name' => "Montserrat", 'country_phone_code' => '+1664', 'country_status' => '1'),
            array('id' => 143, 'country_code' => 'MA', 'country_name' => "Morocco", 'country_phone_code' => '+212', 'country_status' => '1'),
            array('id' => 144, 'country_code' => 'MZ', 'country_name' => "Mozambique", 'country_phone_code' => '+258', 'country_status' => '1'),
            array('id' => 145, 'country_code' => 'MM', 'country_name' => "Myanmar", 'country_phone_code' => '+95', 'country_status' => '1'),
            array('id' => 146, 'country_code' => 'NA', 'country_name' => "Namibia", 'country_phone_code' => '+264', 'country_status' => '1'),
            array('id' => 147, 'country_code' => 'NR', 'country_name' => "Nauru", 'country_phone_code' => '+674', 'country_status' => '1'),
            array('id' => 148, 'country_code' => 'NP', 'country_name' => "Nepal", 'country_phone_code' => '+977', 'country_status' => '1'),
            array('id' => 149, 'country_code' => 'NL', 'country_name' => "Netherlands", 'country_phone_code' => '+31', 'country_status' => '1'),
            array('id' => 150, 'country_code' => 'AN', 'country_name' => "Netherlands Antilles", 'country_phone_code' => '+599', 'country_status' => '1'),
            array('id' => 151, 'country_code' => 'NC', 'country_name' => "New Caledonia", 'country_phone_code' => '+687', 'country_status' => '1'),
            array('id' => 152, 'country_code' => 'NZ', 'country_name' => "New Zealand", 'country_phone_code' => '+64', 'country_status' => '1'),
            array('id' => 153, 'country_code' => 'NI', 'country_name' => "Nicaragua", 'country_phone_code' => '+505', 'country_status' => '1'),
            array('id' => 154, 'country_code' => 'NE', 'country_name' => "Niger", 'country_phone_code' => '+227', 'country_status' => '1'),
            array('id' => 155, 'country_code' => 'NG', 'country_name' => "Nigeria", 'country_phone_code' => '+234', 'country_status' => '1'),
            array('id' => 156, 'country_code' => 'NU', 'country_name' => "Niue", 'country_phone_code' => '+683', 'country_status' => '1'),
            array('id' => 157, 'country_code' => 'NF', 'country_name' => "Norfolk Island", 'country_phone_code' => '+672', 'country_status' => '1'),
            array('id' => 158, 'country_code' => 'KP', 'country_name' => "North Korea", 'country_phone_code' => '+850', 'country_status' => '1'),
            array('id' => 159, 'country_code' => 'MP', 'country_name' => "Northern Mariana Islands", 'country_phone_code' => '+1670', 'country_status' => '1'),
            array('id' => 160, 'country_code' => 'NO', 'country_name' => "Norway", 'country_phone_code' => '+47', 'country_status' => '1'),
            array('id' => 161, 'country_code' => 'OM', 'country_name' => "Oman", 'country_phone_code' => '+968', 'country_status' => '1'),
            array('id' => 162, 'country_code' => 'PK', 'country_name' => "Pakistan", 'country_phone_code' => '+92', 'country_status' => '1'),
            array('id' => 163, 'country_code' => 'PW', 'country_name' => "Palau", 'country_phone_code' => '+680', 'country_status' => '1'),
            array('id' => 164, 'country_code' => 'PS', 'country_name' => "Palestinian Territory", 'country_phone_code' => '+970', 'country_status' => '1'),
            array('id' => 165, 'country_code' => 'PA', 'country_name' => "Panama", 'country_phone_code' => '+507', 'country_status' => '1'),
            array('id' => 166, 'country_code' => 'PG', 'country_name' => "Papua New Guinea", 'country_phone_code' => '+675', 'country_status' => '1'),
            array('id' => 167, 'country_code' => 'PY', 'country_name' => "Paraguay", 'country_phone_code' => '+595', 'country_status' => '1'),
            array('id' => 168, 'country_code' => 'PE', 'country_name' => "Peru", 'country_phone_code' => '+51', 'country_status' => '1'),
            array('id' => 169, 'country_code' => 'PH', 'country_name' => "Philippines", 'country_phone_code' => '+63', 'country_status' => '1'),
            array('id' => 170, 'country_code' => 'PN', 'country_name' => "Pitcairn", 'country_phone_code' => '+870', 'country_status' => '1'),
            array('id' => 171, 'country_code' => 'PL', 'country_name' => "Poland", 'country_phone_code' => '+48', 'country_status' => '1'),
            array('id' => 172, 'country_code' => 'PT', 'country_name' => "Portugal", 'country_phone_code' => '+351', 'country_status' => '1'),
            array('id' => 173, 'country_code' => 'PR', 'country_name' => "Puerto Rico", 'country_phone_code' => '+1787', 'country_status' => '1'),
            array('id' => 174, 'country_code' => 'QA', 'country_name' => "Qatar", 'country_phone_code' => '+974', 'country_status' => '1'),
            array('id' => 175, 'country_code' => 'CG', 'country_name' => "Republic of the Congo", 'country_phone_code' => '+242', 'country_status' => '1'),
            array('id' => 176, 'country_code' => 'RE', 'country_name' => "Reunion", 'country_phone_code' => '+262', 'country_status' => '1'),
            array('id' => 177, 'country_code' => 'RO', 'country_name' => "Romania", 'country_phone_code' => '+40', 'country_status' => '1'),
            array('id' => 178, 'country_code' => 'RU', 'country_name' => "Russia", 'country_phone_code' => '+7', 'country_status' => '1'),
            array('id' => 179, 'country_code' => 'RW', 'country_name' => "Rwanda", 'country_phone_code' => '+250', 'country_status' => '1'),
            array('id' => 180, 'country_code' => 'BL', 'country_name' => "Saint Barthelemy", 'country_phone_code' => '+590', 'country_status' => '1'),
            array('id' => 181, 'country_code' => 'SH', 'country_name' => "Saint Helena", 'country_phone_code' => '+290', 'country_status' => '1'),
            array('id' => 182, 'country_code' => 'KN', 'country_name' => "Saint Kitts and Nevis", 'country_phone_code' => '+1869', 'country_status' => '1'),
            array('id' => 183, 'country_code' => 'LC', 'country_name' => "Saint Lucia", 'country_phone_code' => '+1758', 'country_status' => '1'),
            array('id' => 184, 'country_code' => 'MF', 'country_name' => "Saint Martin", 'country_phone_code' => '+590', 'country_status' => '1'),
            array('id' => 185, 'country_code' => 'PM', 'country_name' => "Saint Pierre and Miquelon", 'country_phone_code' => '+508', 'country_status' => '1'),
            array('id' => 186, 'country_code' => 'VC', 'country_name' => "Saint Vincent and the Grenadines", 'country_phone_code' => '+1784', 'country_status' => '1'),
            array('id' => 187, 'country_code' => 'WS', 'country_name' => "Samoa", 'country_phone_code' => '+685', 'country_status' => '1'),
            array('id' => 188, 'country_code' => 'SM', 'country_name' => "San Marino", 'country_phone_code' => '+378', 'country_status' => '1'),
            array('id' => 189, 'country_code' => 'ST', 'country_name' => "Sao Tome and Principe", 'country_phone_code' => '+239', 'country_status' => '1'),
            array('id' => 190, 'country_code' => 'SA', 'country_name' => "Saudi Arabia", 'country_phone_code' => '+966', 'country_status' => '1'),
            array('id' => 191, 'country_code' => 'SN', 'country_name' => "Senegal", 'country_phone_code' => '+221', 'country_status' => '1'),
            array('id' => 192, 'country_code' => 'RS', 'country_name' => "Serbia", 'country_phone_code' => '+381', 'country_status' => '1'),
            array('id' => 193, 'country_code' => 'SC', 'country_name' => "Seychelles", 'country_phone_code' => '+248', 'country_status' => '1'),
            array('id' => 194, 'country_code' => 'SL', 'country_name' => "Sierra Leone", 'country_phone_code' => '+232', 'country_status' => '1'),
            array('id' => 195, 'country_code' => 'SG', 'country_name' => "Singapore", 'country_phone_code' => '+65', 'country_status' => '1'),
            array('id' => 196, 'country_code' => 'SK', 'country_name' => "Slovakia", 'country_phone_code' => '+421', 'country_status' => '1'),
            array('id' => 197, 'country_code' => 'SI', 'country_name' => "Slovenia", 'country_phone_code' => '+386', 'country_status' => '1'),
            array('id' => 198, 'country_code' => 'SB', 'country_name' => "Solomon Islands", 'country_phone_code' => '+677', 'country_status' => '1'),
            array('id' => 199, 'country_code' => 'SO', 'country_name' => "Somalia", 'country_phone_code' => '+252', 'country_status' => '1'),
            array('id' => 200, 'country_code' => 'ZA', 'country_name' => "South Africa", 'country_phone_code' => '+27', 'country_status' => '1'),
            array('id' => 201, 'country_code' => 'GS', 'country_name' => "South Georgia and the South Sandwich Islands", 'country_phone_code' => '+0', 'country_status' => '1'),
            array('id' => 202, 'country_code' => 'KR', 'country_name' => "South Korea", 'country_phone_code' => '+82', 'country_status' => '1'),
            array('id' => 203, 'country_code' => 'ES', 'country_name' => "Spain", 'country_phone_code' => '+34', 'country_status' => '1'),
            array('id' => 204, 'country_code' => 'LK', 'country_name' => "Sri Lanka", 'country_phone_code' => '+94', 'country_status' => '1'),
            array('id' => 205, 'country_code' => 'SD', 'country_name' => "Sudan", 'country_phone_code' => '+249', 'country_status' => '1'),
            array('id' => 206, 'country_code' => 'SR', 'country_name' => "Suriname", 'country_phone_code' => '+597', 'country_status' => '1'),
            array('id' => 207, 'country_code' => 'SJ', 'country_name' => "Svalbard and Jan Mayen", 'country_phone_code' => '+47', 'country_status' => '1'),
            array('id' => 208, 'country_code' => 'SZ', 'country_name' => "Swaziland", 'country_phone_code' => '+268', 'country_status' => '1'),
            array('id' => 209, 'country_code' => 'SE', 'country_name' => "Sweden", 'country_phone_code' => '+46', 'country_status' => '1'),
            array('id' => 210, 'country_code' => 'CH', 'country_name' => "Switzerland", 'country_phone_code' => '+41', 'country_status' => '1'),
            array('id' => 211, 'country_code' => 'SY', 'country_name' => "Syria", 'country_phone_code' => '+963', 'country_status' => '1'),
            array('id' => 212, 'country_code' => 'TW', 'country_name' => "Taiwan", 'country_phone_code' => '+886', 'country_status' => '1'),
            array('id' => 213, 'country_code' => 'TJ', 'country_name' => "Tajikistan", 'country_phone_code' => '+992', 'country_status' => '1'),
            array('id' => 214, 'country_code' => 'TZ', 'country_name' => "Tanzania", 'country_phone_code' => '+255', 'country_status' => '1'),
            array('id' => 215, 'country_code' => 'TH', 'country_name' => "Thailand", 'country_phone_code' => '+66', 'country_status' => '1'),
            array('id' => 216, 'country_code' => 'TG', 'country_name' => "Togo", 'country_phone_code' => '+228', 'country_status' => '1'),
            array('id' => 217, 'country_code' => 'TK', 'country_name' => "Tokelau", 'country_phone_code' => '+690', 'country_status' => '1'),
            array('id' => 218, 'country_code' => 'TO', 'country_name' => "Tonga", 'country_phone_code' => '+676', 'country_status' => '1'),
            array('id' => 219, 'country_code' => 'TT', 'country_name' => "Trinidad and Tobago", 'country_phone_code' => '+1868', 'country_status' => '1'),
            array('id' => 220, 'country_code' => 'TN', 'country_name' => "Tunisia", 'country_phone_code' => '+216', 'country_status' => '1'),
            array('id' => 221, 'country_code' => 'TR', 'country_name' => "Turkey", 'country_phone_code' => '+90', 'country_status' => '1'),
            array('id' => 222, 'country_code' => 'TM', 'country_name' => "Turkmenistan", 'country_phone_code' => '+993', 'country_status' => '1'),
            array('id' => 223, 'country_code' => 'TC', 'country_name' => "Turks and Caicos Islands", 'country_phone_code' => '+1649', 'country_status' => '1'),
            array('id' => 224, 'country_code' => 'TV', 'country_name' => "Tuvalu", 'country_phone_code' => '+688', 'country_status' => '1'),
            array('id' => 225, 'country_code' => 'UG', 'country_name' => "Uganda", 'country_phone_code' => '+256', 'country_status' => '1'),
            array('id' => 226, 'country_code' => 'UA', 'country_name' => "Ukraine", 'country_phone_code' => '+380', 'country_status' => '1'),
            array('id' => 227, 'country_code' => 'AE', 'country_name' => "United Arab Emirates", 'country_phone_code' => '+971', 'country_status' => '1'),
            array('id' => 228, 'country_code' => 'GB', 'country_name' => "United Kingdom", 'country_phone_code' => '+44', 'country_status' => '1'),
            array('id' => 229, 'country_code' => 'US', 'country_name' => "United States", 'country_phone_code' => '+1', 'country_status' => '1'),
            array('id' => 230, 'country_code' => 'UM', 'country_name' => "United States Minor Outlying Islands", 'country_phone_code' => '+1', 'country_status' => '1'),
            array('id' => 231, 'country_code' => 'UY', 'country_name' => "Uruguay", 'country_phone_code' => '+598', 'country_status' => '1'),
            array('id' => 232, 'country_code' => 'UZ', 'country_name' => "Uzbekistan", 'country_phone_code' => '+998', 'country_status' => '1'),
            array('id' => 233, 'country_code' => 'VU', 'country_name' => "Vanuatu", 'country_phone_code' => '+678', 'country_status' => '1'),
            array('id' => 234, 'country_code' => 'VA', 'country_name' => "Vatican", 'country_phone_code' => '+379', 'country_status' => '1'),
            array('id' => 235, 'country_code' => 'VE', 'country_name' => "Venezuela", 'country_phone_code' => '+58', 'country_status' => '1'),
            array('id' => 236, 'country_code' => 'VN', 'country_name' => "Vietnam", 'country_phone_code' => '+84', 'country_status' => '1'),
            array('id' => 237, 'country_code' => 'WF', 'country_name' => "Wallis and Futuna", 'country_phone_code' => '+681', 'country_status' => '1'),
            array('id' => 238, 'country_code' => 'EH', 'country_name' => "Western Sahara", 'country_phone_code' => '+212', 'country_status' => '1'),
            array('id' => 239, 'country_code' => 'YE', 'country_name' => "Yemen", 'country_phone_code' => '+967', 'country_status' => '1'),
            array('id' => 240, 'country_code' => 'ZM', 'country_name' => "Zambia", 'country_phone_code' => '+260', 'country_status' => '1'),
            array('id' => 241, 'country_code' => 'ZW', 'country_name' => "Zimbabwe", 'country_phone_code' => '+263', 'country_status' => '1')
        );

        DB::table('countries')->insert($countries);
    }
}
